FROM centos:centos7
RUN yum install -y epel-release && \
    yum install -y ansible
RUN yum install -y wget && \
    yum install -y git && \
    yum install -y vim && \
    yum install -y zsh
WORKDIR /root/AnsibleDir/
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true 
COPY ./zsh /root/.oh-my-zsh/custom/plugins
RUN ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
CMD ["/bin/zsh"]

